platform :ios, '14.0'
use_frameworks!

target 'MoodApp' do
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod ‘FirebaseAuth’
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'
  pod 'FirebaseFunctions'




  

end