platform :ios, '14.0'
use_frameworks!

target 'MoodApp' do
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'
  pod 'FirebaseFunctions'
  pod 'GoogleUtilities', '~> 7.11.1'
  
end


target 'IntentsHandler' do
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseAuth'
  pod 'GoogleUtilities', '~> 7.11.1'
end

target 'IntentsHandlerUI' do
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseAuth'
  pod 'GoogleUtilities', '~> 7.11.1'
end